# config.toml
[server]
host = "0.0.0.0"
port = "9602"

[app_settings]
data_dir = "data"  # For user-specific discussion files and SafeStore DBs
database_url = "sqlite:///./app_main.db" # Central SQLite DB for users and app settings
secret_key = "a_very_secret_key_for_flask_sessions_or_jwt" # For potential future session/token use

# Initial admin user to be created in the database if it doesn't exist.
# The password here should be the PLAIN TEXT password you want for the first admin.
# It will be hashed and stored in the database on first startup.
# For subsequent logins, the database's hashed password will be used.
[initial_admin_user]
username = "superadmin"
password = "CHANGE_ME_TO_A_STRONG_PASSWORD" # This will be hashed on first setup

[lollms_client_defaults] # Global defaults, can be overridden by user settings in DB
binding_name = "ollama" # Example: "ollama", "openai", "lollms", "transformers"
default_model_name = "phi3:latest" # Example: "phi3:latest" for ollama, "gpt-4o-mini" for openai
host_address = "http://localhost:11434" # e.g., "http://localhost:11434" for Ollama, "https://api.openai.com/v1" for OpenAI
service_key_env_var = "OPENAI_API_KEY" # Environment variable name for API key (e.g., for OpenAI)
ctx_size = 4096 # Default context size for LLM
user_name = "user" # Default name for the user in prompts
ai_name = "assistant" # Default name for the AI in prompts
# temperature = 0.7 # Optional: Default temperature
# top_k = 50 # Optional: Default top_k
# top_p = 0.95 # Optional: Default top_p

[safe_store_defaults] # Global defaults
chunk_size = 512
chunk_overlap = 50
# Default vectorizer if not set per user. Users can override this.
global_default_vectorizer = "st:all-MiniLM-L6-v2" # Example Sentence Transformer model
# Global encryption key for user SafeStores.
# For per-user encryption keys, you'd store them encrypted in the UserDB (not implemented here).
# If set, requires 'safe_store[encryption]' -> 'cryptography' to be installed.
encryption_key = "my_super_secret_safe_store_key_CHANGE_ME" # Or null/remove to disable encryption
